watch_stylesheet: true
watch_config: true
# debug: true

env_file: ".env"

# This komorebi setting will be used for tray context menu.
# If you don't use komorebi, you can remove this section.
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"
  
# This is the main configuration file for Yet Another Status Bar (YASB)
bars:
  status-bar:
    enabled: true
    #screens: ['DELL P2419H (1)'] 
    #screens: ['DELL P2419H (2)'] 
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false 
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        [
          "home",
          # "komorebi_workspaces",
          "apps",
          "systray",
          "taskbar",
         "active_window"
        ] 
      center: [
        #  "active_window"
        ]
      right:
        [
          "media",
          "traffic",
          "github",
          "cpu",
          "memory",
          # "weather",
          "volume",
          "wifi",
          "battery",
          "clock",
          "power_menu"
        ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue62a</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "D:\\Downloads" }
      - { title: "Documents", path: "C:\\Users\\amn\\Documents" }
      - { title: "Pictures", path: "C:\\Users\\amn\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      offset_top: 6
      offset_left: 0
      container_padding: 
        top: 0
        left: 0
        bottom: 0
        right: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{title} - {artist}"
      max_field_size:
        label: 50
        label_alt: 50
      show_thumbnail: false
      controls_only: false
      controls_left: false
      hide_empty: true
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16 # Set to 0 for square corners
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"

  active_window:
      type: "yasb.active_window.ActiveWindowWidget"
      options:
        label: "{win[title]}"
        label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
        label_no_window: ""
        label_icon: false
        label_icon_size: 16
        max_length: 80
        max_length_ellipsis: "..."
        monitor_exclusive: false

  battery:
      type: "yasb.battery.BatteryWidget"
      options:
        label: "<span>{icon}</span>"
        label_alt: "<span>{icon}</span> {percent}% | Time: {time_remaining}"
        update_interval: 5000
        charging_options:
          icon_format: "{charging_icon}"
        status_icons:
          icon_charging: "󰂄"
          icon_critical: "󰂎"
          icon_low: "󰁺"
          icon_medium: "󰁽"
          icon_high: "󰂁"
          icon_full: "󰁹"
        callbacks:
          on_left: "toggle_label"

  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "{%I:%M:%S<br/>%d/%m/%Y}"
        label_alt: "{%I:%M:%S<br/>%a, %d %b %Y}"
        #locale: 'en_EN' # Langugae for date, you can set your own, example fr_FR
        timezones: [] #Looking up time zone info from registry
        #timezones: ["America/Montreal"]
        callbacks:
          on_middle: "toggle_label"

  cpu:
      type: "yasb.cpu.CpuWidget"
      options:
        label: " \n{info[percent][total]}%"
        label_alt: " {info[histograms][cpu_percent]}"
        update_interval: 2000
        histogram_icons:
          - '\u2581' # 0%
          - '\u2581' # 10%
          - '\u2582' # 20%
          - '\u2583' # 30%
          - '\u2584' # 40%
          - '\u2585' # 50%
          - '\u2586' # 60%
          - '\u2587' # 70%
          - '\u2588' # 80%+
        histogram_num_columns: 8
        callbacks:
          on_right: "exec cmd /c Taskmgr"

  memory:
      type: "yasb.memory.MemoryWidget"
      options:
        label: " \n{virtual_mem_percent}%"
        label_alt: " \n VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
        update_interval: 2000
        callbacks:
          on_right: "exec cmd /c Taskmgr"
          on_middle: "exec \"C:\\Program Files\\Mem\ Reduct\\memreduct.exe\" --clean"

  komorebi_workspaces:
      type: "komorebi.workspaces.WorkspaceWidget"
      options:
          label_offline: "Komorebi Offline"
          label_workspace_btn: "\udb81\udc3d"
          label_workspace_active_btn: "\udb81\udc3e"
          label_default_name: "{index}"
          label_zero_index: false
          hide_empty_workspaces: false
          hide_if_offline: false

  komorebi_active_layout:
      type: "komorebi.active_layout.ActiveLayoutWidget"
      options:
        hide_if_offline: true
        label: "{icon}"
        layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
        layout_icons:
          bsp: "BSP"
          columns: "COLS"
          rows: "ROWS"
          grid: "GRID"
          vertical_stack: "V-STACK"
          horizontal_stack: "H-STACK"
          ultrawide_vertical_stack: "W-STACK"
          right_main_vertical_stack: "RMV-STACK"
          monocle: "MONOCLE"
          maximised: "MAX"
          floating: "FLOATING"
          paused: "PAUSED"
        callbacks:
          on_left: 'next_layout'
          on_middle: 'toggle_monocle'
          on_right: 'prev_layout'

  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "<span>{wifi_icon}</span>"
        label_alt: "<span>{wifi_icon}</span> {wifi_name} {wifi_strength}%"
        update_interval: 5000
        callbacks:
          on_left: "toggle_label"
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network"
        wifi_icons: [
          "\udb82\udd2e",  # Icon for 0% strength
          "\udb82\udd1f",  # Icon for 1-20% strength
          "\udb82\udd22",  # Icon for 21-40% strength
          "\udb82\udd25",  # Icon for 41-80% strength
          "\udb82\udd28"   # Icon for 81-100% strength
        ]

  traffic:
      type: "yasb.traffic.TrafficWidget"
      options:
        # label: "<span>\udb86\uddb3</span>{download_speed} | <span>\udb86\uddb2</span>{upload_speed}"
        label: " {download_speed}\n  {upload_speed}"
        label_alt: "Download {download_speed} \ue621 Upload {upload_speed}"
        update_interval: 1000 # Update interval should be a multiple of 1000
        hide_if_offline: true
        callbacks:
          on_left: "toggle_label"
          # on_right: "exec cmd /c Taskmgr"

  ip_info:
      type: "yasb.custom.CustomWidget"
      options:
        label: "<span>\udb81\udd9f</span> {data[ip]}"
        label_alt: "<span>\uf450</span> {data[city]} {data[region]}, {data[country]}"
        class_name: "ip-info-widget"
        exec_options:
          run_cmd: "curl.exe https://ipinfo.io"
          run_interval: 120000  # every 5 minutes
          return_format: "json"
        callbacks:
          on_left: "toggle_label"
          on_middle: "exec cmd /c ncpa.cpl" # open network settings
          on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser

  weather:
      type: "yasb.weather.WeatherWidget"
      options:
        label: "<span>{icon}</span> {temp}"
        label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
        api_key: '3bf4cf9a7c3f40d6b31174128242807' # Get your free API key from https://www.weatherapi.com/
        update_interval: 600 # Update interval in seconds, Min 600 seconds
        hide_decimal: true
        location: 'Los Angeles, CA, USA' # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
        callbacks:
          on_left: "toggle_label"
        icons: 
          sunnyDay: "\ue30d"
          clearNight: "\ue32b"
          cloudyDay: "\udb81\udd99"
          cloudyNight: "\ue311"
          rainyDay: "\udb81\ude7e"
          rainyNight: "\udb81\ude7e"
          snowyIcyDay: "\udb81\udd98"
          snowyIcyNight: "\udb81\udd98"
          blizzard: "\uebaa"
          default: "\uebaa"
          # https://www.weatherapi.com/docs/
          # Usage {temp}, {min_temp}, {max_temp}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}

  lang:
      type: "yasb.custom.CustomWidget"
      options:
        label: "<span>\uf1ab</span>{data}"
        label_alt: "{data}"
        class_name: "lang-widget"
        exec_options:
          run_cmd: "powershell Add-Type -AssemblyName System.Windows.Forms;([System.Windows.Forms.InputLanguage]::CurrentInputLanguage).Culture.Name"
          # run every 10 sec
          run_interval: 10000
          return_format: "string"

  volume:
      type: "yasb.volume.VolumeWidget"
      options:
        label: "<span>{icon}</span>"
        label_alt: "{volume}"
        volume_icons:
          - ""  # Icon for muted
          - ""  # Icon for 0-10% volume
          - ""  # Icon for 11-30% volume
          - ""  # Icon for 31-60% volume
          - ""  # Icon for 61-100% volume
        callbacks:
          on_left: "toggle_volume_menu"
          on_middle: "toggle_mute"
          on_right: "exec cmd.exe /c start ms-settings:sound"

  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "\uf011"
        uptime: True
        blur: False
        blur_background: True
        animation_duration: 300 # Milisecond 
        button_row: 3 # Number of buttons in row, min 1 max 5
        buttons:
          lock: ["\uea75","Lock"]
          signout: ["\udb80\udf43","Sign out"]
          #sleep: ["\u23fe","Sleep"]
          shutdown: ["\uf011","Shut Down"]
          restart: ["\uead2","Restart"]
          hibernate: ["\uf28e","Hibernate"]
          cancel: ["\udb81\udf3a","Cancel"]
          #force_shutdown: ["\uf011","Force Shut Down"]
          #force_restart: ["\uead2","Force Restart"]

  apps:
      type: "yasb.applications.ApplicationsWidget"
      options:
        label: "{data}"
        app_list:
          - {icon: "\uf489", launch: "wt"}
          - {icon: "\uf413", launch: "explorer c:\\Users\\Piyush"}
          - {icon: "\udb82\ude1e", launch: "C:\\Users\\Piyush\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe"}
          - {icon: "\udb80\ude39", launch: "C:\\Program Files\\Zen Browser\\Zen.exe"}
          - {icon: "\uf1ff", launch: "C:\\Users\\Piyush\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe"}
          - {icon: "󰨇", launch: "taskmgr"}
          #- {icon: "\ue217", launch: "C:\\Users\\amn\\AppData\\Roaming\\Telegram Desktop\\Telegram.exe"}
          # - {icon: "\uf0a2", launch: "notification_center"}
          # - {icon: "\ueb51", launch: "quick_settings"}
          #- {icon: "\uf46a", launch: "cmd.exe /c start ms-settings:windowsupdate"}
          # - {icon: "\uf422", launch: "search"}
          # - {icon: "\udb84\udf55", launch: "widget"}
          # Currently available to use quick_settings, notification_center, search, widget, launcher (launcher will trigger ALT+A)

  github:
      type: "yasb.github.GithubWidget"
      options:
        label: "<span>\ueba1</span>"
        label_alt: "Notifications {data}" # {data} return number of unread notification
        token: env # GitHub Personal access tokens (classic) https://github.com/settings/tokens
        max_notification: 20 # Max number of notification displaying in menu max: 50
        only_unread: false # Show only unread or all notifications; 
        max_field_size: 54 # Max characters in title before truncation.
        update_interval: 1000 # Check for new notification in seconds
        menu:
          blur: False # Enable blur effect for the menu
          round_corners: True # Enable round corners for the menu (this option is not supported on Windows 10)
          round_corners_type: "normal" # Set the type of round corners for the menu (normal, small) (this option is not supported on Windows 10)
          border_color: "System" # Set the border color for the menu (this option is not supported on Windows 10)
          alignment: "right"
          direction: "down"

  wallapers:
      type: "yasb.wallpapers.WallpapersWidget"
      options:
        label: "<span>\udb83\ude09</span>"
        image_path: "C:\\Users\\xxx\\Images" # Path to folder with images
        change_automatically: false # Automatically change wallpaper
        update_interval: 60 # If change_automatically is true, update interval in seconds

  nvidia_temp:
      type: "yasb.custom.CustomWidget"
      options:
        label: "{data}<span>\udb81\udd04</span>"
        label_alt: "{data}"
        class_name: "system-widget"
        exec_options:
          run_cmd: "powershell nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader"
          run_interval: 10000 # run every 10 sec
          return_format: "string"
  
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      animation:
        enabled: true
        duration: 200
        type: "fadeInOut"
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding: 
        top: 0
        left: 8
        bottom: 0
        right: 8

  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "▶"
      label_expanded: "▼"
      label_position: "left" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_battery: false
      show_volume: false
